module = "icon"

[icons]
plus = "plus"
menu = "menu"
history = "history"
star = "star"
group_box = "box"
code_xml = "code-xml"
square_terminal = "square-terminal"
a_large_small = "a-large-small"
pen = "pen"
x = "x"
check = "check"
search = "search"
trash = "trash"
settings = "settings"
sun = "sun"
moon = "moon"
copy = "copy"
play = "play"
square= "square"
chevron_up = "chevron-up"
chevron_down = "chevron-down"
