module = "icon"

[icons]
plus = "plus"
menu = "menu"
history = "history"
star = "star"
group_box = "box"
code_xml = "code-xml"
square_terminal = "square-terminal"
a_large_small = "a-large-small"
pen = "pen"
